"""empty message

Revision ID: dc95c9af7a2e
Revises: 
Create Date: 2019-11-27 23:33:45.938621

"""
from alembic import op
import sqlalchemy as sa
from models import artist1, artist2, artist3, venue1, venue2, venue3, show1, show2, show3, show4, show5


# revision identifiers, used by Alembic.
revision = 'dc95c9af7a2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    artist_table = op.create_table('Artist',
                                   sa.Column('id', sa.Integer(),
                                             nullable=False),
                                   sa.Column('name', sa.String(),
                                             nullable=False),
                                   sa.Column('city', sa.String(
                                       length=120), nullable=False),
                                   sa.Column('state', sa.String(
                                       length=120), nullable=False),
                                   sa.Column('phone', sa.String(
                                       length=120), nullable=False),
                                   sa.Column('seeking_venue',
                                             sa.Boolean(), nullable=False),
                                   sa.Column('seeking_description',
                                             sa.String(), nullable=True),
                                   sa.Column('genres', sa.ARRAY(
                                       sa.String()), nullable=False),
                                   sa.Column('image_link', sa.String(
                                       length=500), nullable=False),
                                   sa.Column('website', sa.String(),
                                             nullable=True),
                                   sa.Column('facebook_link',
                                             sa.String(), nullable=True),
                                   sa.PrimaryKeyConstraint('id')
                                   )
    venue_table = op.create_table('Venue',
                                  sa.Column('id', sa.Integer(),
                                            nullable=False),
                                  sa.Column('name', sa.String(),
                                            nullable=False),
                                  sa.Column('genres', sa.ARRAY(
                                      sa.String()), nullable=False),
                                  sa.Column('address', sa.String(
                                      length=120), nullable=False),
                                  sa.Column('city', sa.String(
                                      length=120), nullable=False),
                                  sa.Column('state', sa.String(
                                      length=120), nullable=False),
                                  sa.Column('phone', sa.String(
                                      length=120), nullable=False),
                                  sa.Column('website', sa.String(
                                      length=120), nullable=False),
                                  sa.Column('facebook_link',
                                            sa.String(), nullable=True),
                                  sa.Column('seeking_talent',
                                            sa.Boolean(), nullable=False),
                                  sa.Column('seeking_description',
                                            sa.String(), nullable=True),
                                  sa.Column('image_link', sa.String(
                                      length=500), nullable=False),
                                  sa.PrimaryKeyConstraint('id')
                                  )
    show_table = op.create_table('Show',
                                 sa.Column('id', sa.Integer(), nullable=False),
                                 sa.Column('venue_id', sa.Integer(),
                                           nullable=False),
                                 sa.Column('artist_id', sa.Integer(),
                                           nullable=False),
                                 sa.Column('start_time',
                                           sa.DateTime(), nullable=False),
                                 sa.ForeignKeyConstraint(
                                     ['artist_id'], ['Artist.id'], onupdate='CASCADE', ondelete='CASCADE'),
                                 sa.ForeignKeyConstraint(
                                     ['venue_id'], ['Venue.id'], onupdate='CASCADE', ondelete='CASCADE'),
                                 sa.PrimaryKeyConstraint('id')
                                 )

    op.bulk_insert(artist_table, [artist1, artist2, artist3])

    op.bulk_insert(venue_table, [venue1, venue2, venue3])

    op.bulk_insert(show_table, [show1, show2, show3, show4, show5])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    op.drop_table('Venue')
    op.drop_table('Artist')
    # ### end Alembic commands ###
