"""add artist id to shows model

Revision ID: e47370e2c776
Revises: 75b6d1bb77d1
Create Date: 2019-11-19 08:00:36.462206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47370e2c776'
down_revision = '75b6d1bb77d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'artist_id')
    # ### end Alembic commands ###
